name: check

on: 
  push:
    branches:
    - feature/*
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  test:
    name: test
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        node: [12, 14, 16, 18]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      timeout-minutes: 1
      with:
        node-version: ${{ matrix.node }}
    - uses: actions/setup-python@v3
      timeout-minutes: 1
      with:
        node-version: ${{ matrix.node }}
    - name: install
      run: npm install
    - name: test
      run: npm run test
